<?php return array (
  'sans-serif' => array(
    'normal' => $fontDir . '/Helvetica',
    'bold' => $fontDir . '/Helvetica-Bold',
    'italic' => $fontDir . '/Helvetica-Oblique',
    'bold_italic' => $fontDir . '/Helvetica-BoldOblique',
  ),
  'times' => array(
    'normal' => $fontDir . '/Times-Roman',
    'bold' => $fontDir . '/Times-Bold',
    'italic' => $fontDir . '/Times-Italic',
    'bold_italic' => $fontDir . '/Times-BoldItalic',
  ),
  'times-roman' => array(
    'normal' => $fontDir . '/Times-Roman',
    'bold' => $fontDir . '/Times-Bold',
    'italic' => $fontDir . '/Times-Italic',
    'bold_italic' => $fontDir . '/Times-BoldItalic',
  ),
  'courier' => array(
    'normal' => $fontDir . '/Courier',
    'bold' => $fontDir . '/Courier-Bold',
    'italic' => $fontDir . '/Courier-Oblique',
    'bold_italic' => $fontDir . '/Courier-BoldOblique',
  ),
  'helvetica' => array(
    'normal' => $fontDir . '/Helvetica',
    'bold' => $fontDir . '/Helvetica-Bold',
    'italic' => $fontDir . '/Helvetica-Oblique',
    'bold_italic' => $fontDir . '/Helvetica-BoldOblique',
  ),
  'zapfdingbats' => array(
    'normal' => $fontDir . '/ZapfDingbats',
    'bold' => $fontDir . '/ZapfDingbats',
    'italic' => $fontDir . '/ZapfDingbats',
    'bold_italic' => $fontDir . '/ZapfDingbats',
  ),
  'symbol' => array(
    'normal' => $fontDir . '/Symbol',
    'bold' => $fontDir . '/Symbol',
    'italic' => $fontDir . '/Symbol',
    'bold_italic' => $fontDir . '/Symbol',
  ),
  'serif' => array(
    'normal' => $fontDir . '/Times-Roman',
    'bold' => $fontDir . '/Times-Bold',
    'italic' => $fontDir . '/Times-Italic',
    'bold_italic' => $fontDir . '/Times-BoldItalic',
  ),
  'monospace' => array(
    'normal' => $fontDir . '/Courier',
    'bold' => $fontDir . '/Courier-Bold',
    'italic' => $fontDir . '/Courier-Oblique',
    'bold_italic' => $fontDir . '/Courier-BoldOblique',
  ),
  'fixed' => array(
    'normal' => $fontDir . '/Courier',
    'bold' => $fontDir . '/Courier-Bold',
    'italic' => $fontDir . '/Courier-Oblique',
    'bold_italic' => $fontDir . '/Courier-BoldOblique',
  ),
  'dejavu sans' => array(
    'bold' => $fontDir . '/DejaVuSans-Bold',
    'bold_italic' => $fontDir . '/DejaVuSans-BoldOblique',
    'italic' => $fontDir . '/DejaVuSans-Oblique',
    'normal' => $fontDir . '/DejaVuSans',
  ),
  'dejavu sans mono' => array(
    'bold' => $fontDir . '/DejaVuSansMono-Bold',
    'bold_italic' => $fontDir . '/DejaVuSansMono-BoldOblique',
    'italic' => $fontDir . '/DejaVuSansMono-Oblique',
    'normal' => $fontDir . '/DejaVuSansMono',
  ),
  'dejavu serif' => array(
    'bold' => $fontDir . '/DejaVuSerif-Bold',
    'bold_italic' => $fontDir . '/DejaVuSerif-BoldItalic',
    'italic' => $fontDir . '/DejaVuSerif-Italic',
    'normal' => $fontDir . '/DejaVuSerif',
  ),
  'open sans' => array(
    'normal' => $fontDir . '/open_sans_normal_bf11512877ef2223afd06e89358ef2fc',
  ),
  'poppins' => array(
    '100_italic' => $fontDir . '/poppins_100_italic_3e6bdece1ffacb38688171766be0924b',
    '200_italic' => $fontDir . '/poppins_200_italic_85ed0ce6f3d82fc16178616514c92f10',
    '300_italic' => $fontDir . '/poppins_300_italic_d20894f03ac9fb76641cc9c969d0525e',
    'italic' => $fontDir . '/poppins_italic_1d694924317a4790716336eefe6b364c',
    '500_italic' => $fontDir . '/poppins_500_italic_88b88e7ee0fd98a6547d793755458e47',
    '600_italic' => $fontDir . '/poppins_600_italic_342424595c018d9856448831a8da64fe',
    'bold_italic' => $fontDir . '/poppins_bold_italic_53d5a4d61eda510ddc454fa1cb2e05ef',
    '100' => $fontDir . '/poppins_100_69a32ecebae5a72c6c9df7538fc2eb96',
    '200' => $fontDir . '/poppins_200_28530177d91bd4ba08b7ffc07cebf559',
    '300' => $fontDir . '/poppins_300_fdf63d9f742346a5ee6b70f5a8af6c01',
    'normal' => $fontDir . '/poppins_normal_c1b7381dfaadf37a84cf14d786076e6d',
    '500' => $fontDir . '/poppins_500_3ab22c79a50a7416f996a1aba688428d',
    '600' => $fontDir . '/poppins_600_270e18a84ac8b306c8f31abe1d0720fa',
    'bold' => $fontDir . '/poppins_bold_7eb29046bc7eaf66b896ec27702d038b',
    '800' => $fontDir . '/poppins_800_536163191f53b5da319f92ee38a84645',
  ),
) ?>